version: "3.0"


services:
  db:
    container_name: "avia_postgres"
    image: postgres:latest
    env_file:
      - ".postgres"
    ports:
      - "5433:5432"
    volumes:
      - "./postgres:/var/lib/postgresql"
      - "./out_data:/data/out"
